[build]
  command = "jekyll build"
  publish = "_site"
  functions = "netlify/functions"

[dev]
  command = "jekyll serve"
  autoLaunch = false
  targetPort = 4000
  port = 8888

[functions]
  external_node_modules = ["airtable"]